# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

BOARD_TAG    = atmega328
#BOARD_TAG    = uno
#ARDUINO_PORT = /dev/tty*
ARDUINO_PORT = /dev/ttyUSB*
ARDUINO_LIBS = AsimiBot PinChangeInt

include $(ARDMK_DIR)/arduino-mk/Arduino.mk
